language: node_js

cache:
  yarn: true
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '8'

script:
  - yarn lint
  - yarn test

deploy:
  provider: script
    skip_cleanup: true
    script:
      - npm run semantic-release
